check npx before run lint script to avoid checking npx in current shell

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,8 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+if ! [ -x "$(command -v npx)" ]; then
+  echo 'Error: npx is not installed.' >&2
+  exit
+fi
 npx --no-install lint-staged
